### ISSUE TITLE
doc: update readthedocs

### ISSUE THREAD

**Issue by ivotron** [uccross/arrow#24]

**Comment by JayjeetAtGithub** [comment]
Being addressed since https://github.com/uccross/arrow/commit/ea2a2f72cf1f9a0e73e51fe6c011deded8086708

**Comment by JayjeetAtGithub** [comment]
Looks like the C++ Datasets API is not exposed in the Documentation. It is exposed only through the Python bindings. So, this depends on #9

**Comment by JayjeetAtGithub** [comment]
Duplicate od #48
